name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        repository: estkme-group/openeuicc
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Build Apks
      working-directory: ./source
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: my-build-apk
        path: ./**/*.apk

    - name: Releasing using Hub
      uses: r0user/release-apk@main
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       APP_FOLDER: app
