name: Android CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        repository: estkme-group/openeuicc
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build Apks
      run: |
        if [ ! -f "gradlew" ]; then gradle wrapper; fi
        sed -i -e '40,42d' app/build.gradle
        sed -i -e '26,33d' app/build.gradle
        sed -i -e '8,11d' app/build.gradle
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: my-build-apk
        path: ./**/*.apk

    - name: Releasing using Hub
      uses: r0user/release-apk@main
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       APP_FOLDER: app
